import assert from "node:assert/strict";
import { test } from "node:test";

import {
  buildGraphSummary,
  buildScriptCatalog,
  parseArgs,
  renderAgentReferenceDoc,
} from "../scripts/generate-agent-reference-docs.mjs";

test("parseArgs reads write, check, stdout, and custom output path", () => {
  const args = parseArgs(["--write", "--check", "--stdout", "--out", "docs/reference/custom.md"]);

  assert.equal(args.write, true);
  assert.equal(args.check, true);
  assert.equal(args.stdout, true);
  assert.equal(args.out, "docs/reference/custom.md");
});

test("buildScriptCatalog groups scripts by stable prefix and sorts commands", () => {
  const catalog = buildScriptCatalog({
    test: "node --test",
    "docs:check": "node scripts/generate-agent-reference-docs.mjs --check",
    "docs:generate": "node scripts/generate-agent-reference-docs.mjs --write",
    "release-notes:preview": "node scripts/generate-release-notes.mjs --stdout",
  });

  assert.deepEqual(
    catalog.map((entry) => ({
      category: entry.category,
      count: entry.count,
      names: entry.entries.map((item) => item.name),
    })),
    [
      {
        category: "docs",
        count: 2,
        names: ["docs:check", "docs:generate"],
      },
      {
        category: "release-notes",
        count: 1,
        names: ["release-notes:preview"],
      },
      {
        category: "test",
        count: 1,
        names: ["test"],
      },
    ],
  );
});

test("buildGraphSummary computes deterministic metrics from graph data", () => {
  const summary = buildGraphSummary({
    nodes: [
      { id: "a", community: 2 },
      { id: "b", community: 2 },
      { id: "c", community: 5 },
    ],
    links: [{ confidence: "EXTRACTED" }, { confidence: "INFERRED" }, { confidence: "INFERRED" }],
  });

  assert.deepEqual(summary, {
    nodeCount: 3,
    edgeCount: 3,
    communityCount: 2,
    confidenceBreakdown: [
      { confidence: "EXTRACTED", count: 1 },
      { confidence: "INFERRED", count: 2 },
    ],
  });
});

test("renderAgentReferenceDoc emits deterministic markdown without timestamps", () => {
  const output = renderAgentReferenceDoc({
    outputPath: "docs/reference/agent-automation-reference.generated.md",
    canonicalDocs: ["AGENTS.md", "docs/system-map.md", "docs/harness-engineering.md"],
    sourceAreas: [
      { area: "cli", path: "src/cli" },
      { area: "executor", path: "src/executor" },
    ],
    scriptCatalog: [
      {
        category: "docs",
        count: 2,
        entries: [
          { name: "docs:check", command: "node scripts/generate-agent-reference-docs.mjs --check" },
          { name: "docs:generate", command: "node scripts/generate-agent-reference-docs.mjs --write" },
        ],
      },
    ],
    graphSummary: {
      nodeCount: 3,
      edgeCount: 3,
      communityCount: 2,
      confidenceBreakdown: [
        { confidence: "EXTRACTED", count: 1 },
        { confidence: "INFERRED", count: 2 },
      ],
    },
  });

  assert.match(output, /# Agent Automation Reference/);
  assert.match(output, /Generated by `npm run docs:generate`/);
  assert.match(output, /\| cli \| `src\/cli` \|/);
  assert.match(output, /## Script Catalog/);
  assert.match(output, /### docs \(2\)/);
  assert.match(output, /## Graph Snapshot/);
  assert.doesNotMatch(output, /Generated on:/);
});
