import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const MINDMAP_JSX = readFileSync(
  join(HERE, "..", "dashboard", "public", "mindmap.jsx"),
  "utf8"
);

describe("mindmap source guard", () => {
  test("background click steps back one layer instead of resetting everything", () => {
    assert.match(MINDMAP_JSX, /const stepBack = \(\) => \{/);
    assert.match(MINDMAP_JSX, /if \(selectedProtocolId\) \{/);
    assert.match(MINDMAP_JSX, /if \(selectedChain\) \{/);
    assert.match(MINDMAP_JSX, /<svg ref=\{svgRef\} width="100%" height="100%" viewBox=\{`0 0 \$\{VB_W\} \$\{VB_H\}`\} preserveAspectRatio="xMidYMid meet" onClick=\{stepBack\}>/);
    assert.doesNotMatch(MINDMAP_JSX, /const resetAll = \(\) => \{ setSelectedChain\(null\); setSelectedProtocolId\(null\); \};/);
  });

  test("mindmap focuses protocols with capital or recent activity and dims siblings on protocol zoom", () => {
    assert.match(MINDMAP_JSX, /if \(!strategy\.protocol\) return false;/);
    assert.match(MINDMAP_JSX, /return strategy\.status === 'LIVE'/);
    assert.match(MINDMAP_JSX, /strategy\.activeStrategyState === 'live_position'/);
    assert.match(MINDMAP_JSX, /return Number\(strategy\.actualProtocolCapitalUsd \|\| 0\) > 0/);
    assert.match(MINDMAP_JSX, /function hasRecentMindmapActivity\(strategy\)/);
    assert.match(MINDMAP_JSX, /return hasRecentMindmapActivity\(strategy\)/);
    assert.match(MINDMAP_JSX, /strategy\.surfaceOnly === 'mindmap'/);
    assert.match(MINDMAP_JSX, /const focusPoint = selectedProtocolId \? \(protocolBloom\[selectedProtocolId\] \|\| null\) : null;/);
    assert.match(MINDMAP_JSX, /const focus = focusPoint/);
    assert.match(MINDMAP_JSX, /function ProtocolAssetMotion\(/);
    assert.match(MINDMAP_JSX, /function uniqueProtocolAssets\(/);
    assert.match(MINDMAP_JSX, /{isSel && \(/);
    assert.match(MINDMAP_JSX, /<ProtocolAssetMotion/);
    assert.match(MINDMAP_JSX, /const dimmed = Boolean\(selectedProtocolId\) && !isSel;/);
    assert.match(MINDMAP_JSX, /const chainDimmed = \(Boolean\(selectedProtocolId\) && active\) \|\| Boolean\(focusedMovementPeer\);/);
    assert.match(MINDMAP_JSX, /opacity: dimmed \? 0\.22 : 1/);
  });

  test("mindmap lane highlighting uses live positions, not historical activity", () => {
    assert.match(MINDMAP_JSX, /function isMindmapActiveStrategy\(strategy\)/);
    assert.match(MINDMAP_JSX, /\.filter\(\(strategy\) => isMindmapActiveStrategy\(strategy\)\)/);
    assert.match(MINDMAP_JSX, /Array\.isArray\(window\.FLOW\?\.recentMovements\)/);
    assert.match(MINDMAP_JSX, /const MINDMAP_RECENT_MOVEMENT_TTL_MS = 6 \* 60 \* 60 \* 1000;/);
    assert.match(MINDMAP_JSX, /const MAX_ROOT_MOVEMENT_TRACKS = 2;/);
    assert.match(MINDMAP_JSX, /const MAX_FOCUSED_MOVEMENT_TRACKS = 12;/);
    assert.match(MINDMAP_JSX, /const MOVEMENT_NODE_GAP = 28;/);
    assert.match(MINDMAP_JSX, /const MOVEMENT_GATEWAY_GAP = 22;/);
    assert.match(MINDMAP_JSX, /const MOVEMENT_ROUTE_COLORS = Object\.freeze\(\[/);
    assert.match(MINDMAP_JSX, /'#0057FF'/);
    assert.match(MINDMAP_JSX, /'#00A86B'/);
    assert.match(MINDMAP_JSX, /'#FFB000'/);
    assert.match(MINDMAP_JSX, /function isRecentMovement\(movement, nowMs = Date\.now\(\)\)/);
    assert.match(MINDMAP_JSX, /function movementFreshness\(movement, nowMs = Date\.now\(\)\)/);
    assert.match(MINDMAP_JSX, /function dedupeRecentMovements\(movements = \[\]\)/);
    assert.match(MINDMAP_JSX, /function movementDedupeKey\(movement = \{\}\)/);
    assert.match(MINDMAP_JSX, /function shortChainName\(chainId\)/);
    assert.match(MINDMAP_JSX, /const provider = movement\.routeProvider \|\| movement\.kind \|\| 'movement';/);
    assert.match(MINDMAP_JSX, /return movement\.routeKey/);
    assert.match(MINDMAP_JSX, /\? `\$\{provider\}:\$\{movement\.routeKey\}`/);
    assert.match(MINDMAP_JSX, /: `\$\{provider\}:\$\{movement\.fromChainId\}->\$\{movement\.toChainId\}:\$\{movement\.assetId \|\| 'asset'\}`/);
    assert.match(MINDMAP_JSX, /const recentMovements = dedupeRecentMovements\(/);
    assert.match(MINDMAP_JSX, /\.sort\(\(left, right\) => new Date\(right\.observedAt \|\| 0\) - new Date\(left\.observedAt \|\| 0\)\)/);
    assert.match(MINDMAP_JSX, /function movementUsesGateway\(movement = \{\}\)/);
    assert.match(MINDMAP_JSX, /return MOVEMENT_ROUTE_COLORS\[index % MOVEMENT_ROUTE_COLORS\.length\]/);
    assert.match(MINDMAP_JSX, /function movementLaneOffset\(laneIndex = 0, totalTracks = 1, segmentIndex = 0\)/);
    assert.match(MINDMAP_JSX, /const centered = laneIndex - \(total - 1\) \/ 2;/);
    assert.match(MINDMAP_JSX, /function trimSegmentEndpoints\(from, to, startGap = 0, endGap = 0\)/);
    assert.match(MINDMAP_JSX, /function movementLinePath\(from, to, startGap = MOVEMENT_NODE_GAP, endGap = MOVEMENT_NODE_GAP, laneIndex = 0, segmentIndex = 0, totalTracks = 1\)/);
    assert.match(MINDMAP_JSX, /const offset = movementLaneOffset\(laneIndex, totalTracks, segmentIndex\);/);
    assert.match(MINDMAP_JSX, /d: `M \$\{trimmed\.from\.x\} \$\{trimmed\.from\.y\} Q \$\{cx\} \$\{cy\} \$\{trimmed\.to\.x\} \$\{trimmed\.to\.y\}`/);
    assert.doesNotMatch(MINDMAP_JSX, /function movementEndpointLabelPoint/);
    assert.doesNotMatch(MINDMAP_JSX, /function directCurvePath/);
    assert.doesNotMatch(MINDMAP_JSX, /function MovementEndpointLabel/);
    assert.doesNotMatch(MINDMAP_JSX, /data-movement-endpoint-label/);
    assert.doesNotMatch(MINDMAP_JSX, /function MovementChainAccent/);
    assert.doesNotMatch(MINDMAP_JSX, /data-movement-chain-accent/);
    assert.doesNotMatch(MINDMAP_JSX, /movementAccent=/);
    assert.doesNotMatch(MINDMAP_JSX, /function MovementAssetOnTrack/);
    assert.doesNotMatch(MINDMAP_JSX, /MOVEMENT_ASSET_SIZE/);
    assert.doesNotMatch(MINDMAP_JSX, /MOVEMENT_ASSET_SECONDS/);
    assert.doesNotMatch(MINDMAP_JSX, /movementAssetSizeForCount/);
    assert.doesNotMatch(MINDMAP_JSX, /<animateMotion/);
    assert.match(MINDMAP_JSX, /function MovementTrail\(\{ track, selectedChain \}\)/);
    assert.match(MINDMAP_JSX, /const selected = Boolean\(selectedChain\);/);
    assert.match(MINDMAP_JSX, /const projectedOpacityScale = track\.projected \? \(selected \? 0\.22 : 0\.42\) : 1;/);
    assert.match(MINDMAP_JSX, /const projectedStrokeScale = track\.projected \? 0\.62 : 1;/);
    assert.match(MINDMAP_JSX, /const opacity = \(selected \? 0\.24 \+ freshness \* 0\.42 : 0\.12 \+ freshness \* 0\.42\) \* projectedOpacityScale;/);
    assert.match(MINDMAP_JSX, /const strokeWidth = \(selected \? 0\.92 \+ freshness \* 0\.28 : 0\.72 \+ freshness \* 0\.3\) \* crowdedStrokeScale \* projectedStrokeScale;/);
    assert.match(MINDMAP_JSX, /markerWidth="5\.6" markerHeight="5\.6" refX="5\.1" refY="2\.8"/);
    assert.match(MINDMAP_JSX, /markerEnd=\{segmentIndex === track\.segments\.length - 1 \? `url\(#\$\{arrowId\}\)` : undefined\}/);
    assert.match(MINDMAP_JSX, /strokeDasharray=\{track\.viaGateway \? '3 5' : '3 6'\}/);
    assert.match(MINDMAP_JSX, /track\.segments\.map\(\(segment, segmentIndex\) => \(/);
    assert.match(MINDMAP_JSX, /<path id=\{`movement-motion-\$\{track\.index\}`\}/);
    assert.match(MINDMAP_JSX, /projected: movement\.projected === true/);
    assert.doesNotMatch(MINDMAP_JSX, /<MovementAssetOnTrack/);
    assert.match(MINDMAP_JSX, /\{!selectedChain && destChains\.filter\(c => liveChains\.has\(c\.id\)\)\.map\(\(c, idx\) => \{/);
    assert.doesNotMatch(MINDMAP_JSX, /liveChains\.has\(c\.id\) \|\| \(selectedChain && focusedMovementChainIds\.has\(c\.id\)\)/);
    assert.doesNotMatch(MINDMAP_JSX, /const tokenSize = selectedChain/);
    assert.match(MINDMAP_JSX, /if \(viaGateway\) \{/);
    assert.match(MINDMAP_JSX, /const inbound = movementLinePath\(from, gateway, MOVEMENT_NODE_GAP, MOVEMENT_GATEWAY_GAP, index, 0, totalTracks\);/);
    assert.match(MINDMAP_JSX, /const outbound = movementLinePath\(gateway, to, MOVEMENT_GATEWAY_GAP, MOVEMENT_NODE_GAP, index, 1, totalTracks\);/);
    assert.match(MINDMAP_JSX, /motionD = `\$\{inbound\.d\} L \$\{outbound\.x1\} \$\{outbound\.y1\} Q \$\{outbound\.cx\} \$\{outbound\.cy\} \$\{outbound\.x2\} \$\{outbound\.y2\}`;/);
    assert.match(MINDMAP_JSX, /const direct = movementLinePath\(from, to, MOVEMENT_NODE_GAP, MOVEMENT_NODE_GAP, index, 0, totalTracks\)/);
    assert.doesNotMatch(MINDMAP_JSX, /endpoints: \[/);
    assert.doesNotMatch(MINDMAP_JSX, /function buildMovementChainAccents/);
    assert.match(MINDMAP_JSX, /const visibleMovementSeeds = \(selectedChain/);
    assert.match(MINDMAP_JSX, /\.slice\(0, selectedChain \? MAX_FOCUSED_MOVEMENT_TRACKS : MAX_ROOT_MOVEMENT_TRACKS\);/);
    assert.match(MINDMAP_JSX, /\.map\(\(movement, index\) => buildMovementTrack\(movement, index, visibleMovementSeeds\.length\)\)/);
    assert.match(MINDMAP_JSX, /selectedChain=\{selectedChain\}/);
    assert.match(MINDMAP_JSX, /const movementChains = new Set\(/);
    assert.match(MINDMAP_JSX, /movementChains\.has\(c\.id\)/);
    assert.match(MINDMAP_JSX, /const focusedMovements = selectedChain/);
    assert.match(MINDMAP_JSX, /const focusedMovementChainIds = new Set\(/);
    assert.match(MINDMAP_JSX, /const focusedMovementUsesGateway = focusedMovements\.some\(\(movement\) => movementUsesGateway\(movement\)\);/);
    assert.match(MINDMAP_JSX, /function isGatewayProtocolGroup\(strategy = \{\}\)/);
    assert.match(MINDMAP_JSX, /groupStrategiesByProtocol\(strategies\)\.filter\(\(group\) => !isGatewayProtocolGroup\(group\)\)/);
    assert.match(MINDMAP_JSX, /const selectedChainUsesGatewayProtocol = Boolean\(selectedChain\)/);
    assert.match(MINDMAP_JSX, /const focusedGatewayVisible = focusedMovementUsesGateway \|\| selectedChainUsesGatewayProtocol;/);
    assert.match(MINDMAP_JSX, /const focusedMovementPeer = selectedChain && focusedMovementChainIds\.has\(c\.id\);/);
    assert.match(MINDMAP_JSX, /const hidden = selectedChain && selectedChain !== c\.id && !focusedMovementPeer;/);
    assert.match(MINDMAP_JSX, /const hidden = selectedChain && !active && !focusedMovementPeer;/);
    assert.match(MINDMAP_JSX, /function GatewayCore\(\{ size, hidden, compact = false \}\)/);
    assert.match(MINDMAP_JSX, /const visualSize = compact \? size \* 0\.58 : size;/);
    assert.match(MINDMAP_JSX, /\{!compact && \(\s*<text y=\{h\/2 \+ 10\}/s);
    assert.match(MINDMAP_JSX, /function ChainNode\(\{ chain, x, y, size, hidden, active, dimmed = false, compact = false,/);
    assert.match(MINDMAP_JSX, /const visualSize = compact \? size \* 0\.5 : size;/);
    assert.match(MINDMAP_JSX, /\{!compact && \(\s*<>\s*<text y=\{nameY\}/s);
    assert.match(MINDMAP_JSX, /compact=\{Boolean\(focusedMovementPeer && !active\)\}/);
    assert.match(MINDMAP_JSX, /<GatewayCore size=\{gatewaySize\} hidden=\{Boolean\(selectedChain\) && !focusedGatewayVisible\} compact=\{Boolean\(selectedChain\)\}\/>/);
    assert.match(MINDMAP_JSX, /includeCircle\(bounds, 0, 0, gatewaySize \* 0\.95\);/);
    assert.match(MINDMAP_JSX, /includeCircle\(bounds, point\.x, point\.y, chainSize \* 0\.46\);/);
    assert.match(MINDMAP_JSX, /focusedMovementChainIds\.forEach\(\(chainId\) => \{/);
    assert.doesNotMatch(MINDMAP_JSX, /movementChainAccents/);
    assert.doesNotMatch(MINDMAP_JSX, /size\/2 \+ 4\.2/);
    assert.doesNotMatch(MINDMAP_JSX, /track\.segments\.map\(\(segment, segmentIndex\) => \(\s*<MovementAssetOnSegment/);
    assert.doesNotMatch(MINDMAP_JSX, /key=\{`movement-src-\$\{movement\.id \|\| idx\}`\}/);
    assert.doesNotMatch(MINDMAP_JSX, /key=\{`movement-dst-\$\{movement\.id \|\| idx\}`\}/);
    assert.doesNotMatch(MINDMAP_JSX, /visibleMovements\.map/);
    assert.doesNotMatch(MINDMAP_JSX, /function FlowTokenOnSegments/);
    assert.doesNotMatch(MINDMAP_JSX, /function MovementRouteLabel/);
    assert.doesNotMatch(MINDMAP_JSX, /function MovementContextPanel/);
    assert.doesNotMatch(MINDMAP_JSX, /data-card-type="movement-context"/);
    assert.doesNotMatch(MINDMAP_JSX, /strokeDashoffset/);
    assert.doesNotMatch(MINDMAP_JSX, /movementGlow/);
    assert.doesNotMatch(MINDMAP_JSX, /const MOVEMENT_COLORS = Object\.freeze\(\{/);
    assert.doesNotMatch(MINDMAP_JSX, /\.filter\(\(strategy\) => strategy\.status === 'LIVE' \|\| Number\(strategy\.recentActivityCount \|\| 0\) > 0\)/);
  });

  test("chain and protocol nodes render compact USD pills and bounded protocol cards", () => {
    assert.match(MINDMAP_JSX, /function StatPill\(/);
    assert.match(MINDMAP_JSX, /function formatYieldDisplay\(/);
    assert.match(MINDMAP_JSX, /function weightedProtocolApr\(strategies = \[\]\)/);
    assert.match(MINDMAP_JSX, /function aprWeightUsd\(strategy\)/);
    assert.match(MINDMAP_JSX, /const weightedRows = rows\.filter\(\(strategy\) => aprWeightUsd\(strategy\) > 0\)/);
    assert.match(MINDMAP_JSX, /return rows\.reduce\(\(sum, strategy\) => sum \+ strategy\.apyPct, 0\) \/ rows\.length/);
    assert.match(MINDMAP_JSX, /apyPct: weightedProtocolApr\(items\)/);
    assert.match(MINDMAP_JSX, /const PROTOCOL_CARD_MAX_HEIGHT = 132;/);
    assert.match(MINDMAP_JSX, /const PROTOCOL_CARD_SAFE_BOTTOM = 188;/);
    assert.match(MINDMAP_JSX, /const PROTOCOL_CHIP_SIZE = 30;/);
    assert.match(MINDMAP_JSX, /const PROTOCOL_BLOOM_MIN_RADIUS = 112;/);
    assert.match(MINDMAP_JSX, /const PROTOCOL_BLOOM_PADDING = 22;/);
    assert.match(MINDMAP_JSX, /\.\.\.items\.map\(\(item\) => Number\(item\.actualProtocolCapitalUsd \|\| 0\)\)/);
    assert.match(MINDMAP_JSX, /const capitalLabel = formatCompactUsdLabel\(Number\(strategy\.capitalUsd \|\| 0\)\)/);
    assert.match(MINDMAP_JSX, /const chainAvailableUsd = Number\(window\.CAPITAL\?\.walletByChain\?\.\[chainId\] \|\| 0\)/);
    assert.match(MINDMAP_JSX, /const chainDeployedUsd = Number\(window\.CAPITAL\?\.deployedByChain\?\.\[chainId\] \|\| 0\)/);
    assert.match(MINDMAP_JSX, /const chainTotalUsd = chainAvailableUsd \+ chainDeployedUsd/);
    assert.match(MINDMAP_JSX, /<Metric label="Free" value=\{formatCompactUsdLabel\(chainAvailableUsd\) \|\| '—'\}\/>/);
    assert.match(MINDMAP_JSX, /<Metric label="Deployed" value=\{formatCompactUsdLabel\(chainDeployedUsd\) \|\| '—'\}\/>/);
    assert.match(MINDMAP_JSX, /<Metric label="Total" value=\{capitalLabel \|\| '—'\}\/>/);
    assert.match(MINDMAP_JSX, /<Metric label="Moved 6h" value=\{formatCompactUsdLabel\(chain\.recentMovementUsd\) \|\| `\$\{chain\.recentMovementCount\} tx`\}\/>/);
    assert.match(MINDMAP_JSX, /const capitalY = labelBelow \? visualSize \* 1\.46 : -visualSize \* 1\.34;/);
    assert.match(MINDMAP_JSX, /includeRect\(bounds, point\.x, point\.y - chipRadius - 19, 62, 16\)/);
    assert.match(MINDMAP_JSX, /includeRect\(bounds, point\.x, point\.y - chipSize \* 2\.48, 48, 18\)/);
    assert.match(MINDMAP_JSX, /yieldMetricLabel\(protocolNode\.yieldBasis\)/);
    assert.match(MINDMAP_JSX, /maxHeight: PROTOCOL_CARD_MAX_HEIGHT/);
    assert.match(MINDMAP_JSX, /const protocolAssets = Array\.from\(new Set\(\[/);
    assert.match(MINDMAP_JSX, /protocolNode\.recentActivityAssets/);
    assert.doesNotMatch(MINDMAP_JSX, /const visibleStrategies = protocolNode\.strategies\.slice\(0, PROTOCOL_CARD_STRATEGY_PREVIEW_COUNT\);/);
    assert.doesNotMatch(MINDMAP_JSX, />Pair<\/span>/);
    assert.doesNotMatch(MINDMAP_JSX, /<Metric label="Mapped"/);
    assert.doesNotMatch(MINDMAP_JSX, /\+\{hiddenStrategyCount\} more/);
    assert.doesNotMatch(MINDMAP_JSX, /activeProtocolCount/);
    assert.doesNotMatch(MINDMAP_JSX, /activeProtocolCountsByChain/);
    assert.doesNotMatch(MINDMAP_JSX, /#19A35B/);
  });

  test("selected protocol view keeps asset motion logo-only without duplicate pair text", () => {
    assert.match(MINDMAP_JSX, /function AssetLogoTag\(/);
    assert.doesNotMatch(MINDMAP_JSX, /function AssetTickerPill\(/);
    assert.doesNotMatch(MINDMAP_JSX, /join\(' \/ '\)/);
    assert.doesNotMatch(MINDMAP_JSX, /strategy\.strategies\?\.\[0\]\?\.label \|\| strategy\.label \|\| strategy\.protocol/);
  });

  test("focus mode dampens motion on zoomed protocol views", () => {
    assert.match(MINDMAP_JSX, /const focusMotionScale = selectedProtocolId \? 0\.16 : selectedChain \? 0\.34 : 1;/);
    assert.match(MINDMAP_JSX, /const settlePull = selectedProtocolId \? 0\.18 : selectedChain \? 0\.08 : 0;/);
    assert.match(MINDMAP_JSX, /b\.x \+= \(b\.anchorX - b\.x\) \* settlePull;/);
  });
});
