export const EVM_CHAINS = {
  avalanche: {
    nativeSymbol: "AVAX",
    nativePriceKey: "avalanche",
    rpcUrl: "https://api.avax.network/ext/bc/C/rpc",
    rpcUrls: ["https://api.avax.network/ext/bc/C/rpc"],
    fallbackGasUnits: 260_000,
  },
  base: {
    nativeSymbol: "ETH",
    nativePriceKey: "base",
    rpcUrl: "https://mainnet.base.org",
    rpcUrls: ["https://mainnet.base.org"],
    fallbackGasUnits: 260_000,
  },
  bera: {
    nativeSymbol: "BERA",
    nativePriceKey: "bera",
    rpcUrl: "https://rpc.berachain.com",
    rpcUrls: ["https://rpc.berachain.com"],
    fallbackGasUnits: 260_000,
  },
  bob: {
    nativeSymbol: "ETH",
    nativePriceKey: "bob",
    rpcUrl: "https://rpc.gobob.xyz",
    rpcUrls: ["https://rpc.gobob.xyz"],
    fallbackGasUnits: 260_000,
  },
  bsc: {
    nativeSymbol: "BNB",
    nativePriceKey: "bsc",
    rpcUrl: "https://bsc-dataseed.binance.org",
    rpcUrls: ["https://bsc-dataseed.binance.org"],
    fallbackGasUnits: 260_000,
  },
  ethereum: {
    nativeSymbol: "ETH",
    nativePriceKey: "ethereum",
    rpcUrl: "https://ethereum-rpc.publicnode.com",
    rpcUrls: ["https://ethereum-rpc.publicnode.com"],
    fallbackGasUnits: 260_000,
  },
  soneium: {
    nativeSymbol: "ETH",
    nativePriceKey: "soneium",
    rpcUrl: "https://rpc.soneium.org",
    rpcUrls: ["https://rpc.soneium.org"],
    fallbackGasUnits: 260_000,
  },
  sonic: {
    nativeSymbol: "S",
    nativePriceKey: "sonic",
    rpcUrl: "https://rpc.soniclabs.com",
    rpcUrls: ["https://rpc.soniclabs.com"],
    fallbackGasUnits: 260_000,
  },
  unichain: {
    nativeSymbol: "ETH",
    nativePriceKey: "unichain",
    rpcUrl: "https://mainnet.unichain.org",
    rpcUrls: ["https://mainnet.unichain.org"],
    fallbackGasUnits: 260_000,
  },
};
